### ISSUE TITLE
UnboundLocalError: local variable 'L2type' referenced before assignment

### ISSUE THREAD

**Issue by bim2010** [olivierhagolle/Start_maja#21]
Hi Olivier,
Here is command I'm typing in:
`python start_maja.py -f folders.txt -c MAJA_1_0_S2AS2B_NATIF -t T36UVG -s T36UVG -d 20180503`
[GIPP_MAJA_1_0_S2AS2B_NATIF ](https://cloud.mail.ru/public/6HrQ/op2241rTX)
maja output:
```
root@localhost Start_maja]# python start_maja.py -f folders.txt -c MAJA_1_0_S2AS2B_NATIF -t T36UVG -s T36UVG -d 20180503
['/opt/maja/Start_maja', '/usr/lib64/python27.zip', '/usr/lib64/python2.7', '/usr/lib64/python2.7/plat-linux2', '/usr/lib64/python2.7/lib-tk', '/usr/lib64/python2.7/lib-old', '/usr/lib64/python2.7/lib-dynload', '/usr/lib64/python2.7/site-packages', '/usr/lib64/python2.7/site-packages/gtk-2.0', '/usr/lib/python2.7/site-packages']

2018-11-14 09:11:14,895 - Start-Maja - INFO - No existing L2 product, we start with backward mode
2018-11-14 09:11:14,896 - Start-Maja - INFO - => processing date 20180503
2018-11-14 09:11:14,897 - Start-Maja - INFO - dates to process in backward mode :
2018-11-14 09:11:14,897 - Start-Maja - INFO - -- 20180503 : /opt/maja/repL1/T36UVG/S2B_MSIL1C_20180503T085559_N0206_R007_T36UVG_20180503T115055.SAFE
2018-11-14 09:11:14,898 - Start-Maja - INFO - -- 20180508 : /opt/maja/repL1/T36UVG/S2A_MSIL1C_20180508T085601_N0206_R007_T36UVG_20180508T141842.SAFE
2018-11-14 09:11:14,898 - Start-Maja - INFO - -- 20180511 : /opt/maja/repL1/T36UVG/S2A_MSIL1C_20180511T090601_N0206_R050_T36UVG_20180511T103619.SAFE
2018-11-14 09:11:14,898 - Start-Maja - INFO - -- 20180513 : /opt/maja/repL1/T36UVG/S2B_MSIL1C_20180513T085559_N0206_R007_T36UVG_20180513T110715.SAFE
2018-11-14 09:11:14,898 - Start-Maja - INFO - -- 20180521 : /opt/maja/repL1/T36UVG/S2A_MSIL1C_20180521T090601_N0206_R050_T36UVG_20180521T104113.SAFE
2018-11-14 09:11:14,899 - Start-Maja - INFO - -- 20180526 : /opt/maja/repL1/T36UVG/S2B_MSIL1C_20180526T091019_N0206_R050_T36UVG_20180526T125255.SAFE
2018-11-14 09:11:14,899 - Start-Maja - INFO - -- 20180528 : /opt/maja/repL1/T36UVG/S2A_MSIL1C_20180528T085641_N0206_R007_T36UVG_20180528T103122.SAFE
2018-11-14 09:11:14,899 - Start-Maja - INFO - -- 20180531 : /opt/maja/repL1/T36UVG/S2A_MSIL1C_20180531T091031_N0206_R050_T36UVG_20180531T111240.SAFE
2018-11-14 09:11:14,908 - Start-Maja - INFO - #################################
2018-11-14 09:11:14,909 - Start-Maja - INFO - #################################
2018-11-14 09:11:14,909 - Start-Maja - INFO - processing /opt/maja/repL1/T36UVG/S2B_MSIL1C_20180503T085559_N0206_R007_T36UVG_20180503T115055.SAFE in backward mode
2018-11-14 09:11:14,909 - Start-Maja - INFO - Initialisation mode with backward is longer
2018-11-14 09:11:14,909 - Start-Maja - INFO - MAJA logfile: /opt/maja/repL2/T36UVG/T36UVG/MAJA_1_0_S2AS2B_NATIF//S2B_MSIL1C_20180503T085559_N0206_R007_T36UVG_20180503T115055.SAFE.log
2018-11-14 09:11:14,909 - Start-Maja - INFO - #################################
2018-11-14 11:46:53,016 - Start-Maja - INFO - => processing date 20180508
Traceback (most recent call last):
  File "start_maja.py", line 536, in <module>
    start_maja(folder_file, context, site, tile, orbit, nb_backward, options, debug_mode)
  File "start_maja.py", line 395, in start_maja
    logger.info("Using %s L2 type"%L2type)     
UnboundLocalError: local variable 'L2type' referenced before assignment
[root@localhost Start_maja]#
```

Happy GIS Day!

Best regards,
Igor
[S2B_MSIL1C_20180503T085559_N0206_R007_T36UVG_20180503T115055.SAFE.log](https://github.com/olivierhagolle/Start_maja/files/2580107/S2B_MSIL1C_20180503T085559_N0206_R007_T36UVG_20180503T115055.SAFE.log)

**Comment by olivierhagolle** [comment]
Hi Igor,
before spending time on this, just wondering if you paid attention to the first lines of the readme file : 

NB Start maja has been updated to work with MAJA 3.1 , but MAJA 3.1 is not available yet. Meanwhile, please use MAJA 1_0, and read the corresponding readme file. To do that, please use git checkout Start_maja_V1.

So did you use  `git checkout Start_maja_V1` ?
Olivier

**Comment by bim2010** [comment]
Changed to this release https://github.com/olivierhagolle/Start_maja/tree/Start_maja_V1
MAJA output:
```
[root@localhost Start_maja]# python start_maja.py -f folders.txt -c MAJA_1_0_S2AS2B_NATIF -t T36UVG -s T36UVG -d 20180503
/opt/maja/repL1/T36UVG/S2A_MSIL1C_20180531T091031_N0206_R050_T36UVG_20180531T111240.SAFE
S2A_MSIL1C_20180531T091031_N0206_R050_T36UVG_20180531T111240.SAFE
20180531
/opt/maja/repL1/T36UVG/S2A_MSIL1C_20180528T085641_N0206_R007_T36UVG_20180528T103122.SAFE
S2A_MSIL1C_20180528T085641_N0206_R007_T36UVG_20180528T103122.SAFE
20180528
/opt/maja/repL1/T36UVG/S2B_MSIL1C_20180503T085559_N0206_R007_T36UVG_20180503T115055.SAFE
S2B_MSIL1C_20180503T085559_N0206_R007_T36UVG_20180503T115055.SAFE
20180503
/opt/maja/repL1/T36UVG/S2A_MSIL1C_20180521T090601_N0206_R050_T36UVG_20180521T104113.SAFE
S2A_MSIL1C_20180521T090601_N0206_R050_T36UVG_20180521T104113.SAFE
20180521
/opt/maja/repL1/T36UVG/S2A_MSIL1C_20180511T090601_N0206_R050_T36UVG_20180511T103619.SAFE
S2A_MSIL1C_20180511T090601_N0206_R050_T36UVG_20180511T103619.SAFE
20180511
/opt/maja/repL1/T36UVG/S2B_MSIL1C_20180526T091019_N0206_R050_T36UVG_20180526T125255.SAFE
S2B_MSIL1C_20180526T091019_N0206_R050_T36UVG_20180526T125255.SAFE
20180526
/opt/maja/repL1/T36UVG/S2A_MSIL1C_20180508T085601_N0206_R007_T36UVG_20180508T141842.SAFE
S2A_MSIL1C_20180508T085601_N0206_R007_T36UVG_20180508T141842.SAFE
20180508
/opt/maja/repL1/T36UVG/S2B_MSIL1C_20180513T085559_N0206_R007_T36UVG_20180513T110715.SAFE
S2B_MSIL1C_20180513T085559_N0206_R007_T36UVG_20180513T110715.SAFE
20180513
20180503T085559 2
20180503 /opt/maja/repL1/T36UVG/S2B_MSIL1C_20180503T085559_N0206_R007_T36UVG_20180503T115055.SAFE
20180508T085601 6
20180508 /opt/maja/repL1/T36UVG/S2A_MSIL1C_20180508T085601_N0206_R007_T36UVG_20180508T141842.SAFE
20180511T090601 4
20180511 /opt/maja/repL1/T36UVG/S2A_MSIL1C_20180511T090601_N0206_R050_T36UVG_20180511T103619.SAFE
20180513T085559 7
20180513 /opt/maja/repL1/T36UVG/S2B_MSIL1C_20180513T085559_N0206_R007_T36UVG_20180513T110715.SAFE
20180521T090601 3
20180521 /opt/maja/repL1/T36UVG/S2A_MSIL1C_20180521T090601_N0206_R050_T36UVG_20180521T104113.SAFE
20180526T091019 5
20180526 /opt/maja/repL1/T36UVG/S2B_MSIL1C_20180526T091019_N0206_R050_T36UVG_20180526T125255.SAFE
20180528T085641 1
20180528 /opt/maja/repL1/T36UVG/S2A_MSIL1C_20180528T085641_N0206_R007_T36UVG_20180528T103122.SAFE
20180531T091031 0
20180531 /opt/maja/repL1/T36UVG/S2A_MSIL1C_20180531T091031_N0206_R050_T36UVG_20180531T111240.SAFE

#### dates à traiter 20180503
/opt/maja/repL1/T36UVG/S2B_MSIL1C_20180503T085559_N0206_R007_T36UVG_20180503T115055.SAFE
#### dates à traiter 20180508
/opt/maja/repL1/T36UVG/S2A_MSIL1C_20180508T085601_N0206_R007_T36UVG_20180508T141842.SAFE
#### dates à traiter 20180511
/opt/maja/repL1/T36UVG/S2A_MSIL1C_20180511T090601_N0206_R050_T36UVG_20180511T103619.SAFE
#### dates à traiter 20180513
/opt/maja/repL1/T36UVG/S2B_MSIL1C_20180513T085559_N0206_R007_T36UVG_20180513T110715.SAFE
#### dates à traiter 20180521
/opt/maja/repL1/T36UVG/S2A_MSIL1C_20180521T090601_N0206_R050_T36UVG_20180521T104113.SAFE
#### dates à traiter 20180526
/opt/maja/repL1/T36UVG/S2B_MSIL1C_20180526T091019_N0206_R050_T36UVG_20180526T125255.SAFE
#### dates à traiter 20180528
/opt/maja/repL1/T36UVG/S2A_MSIL1C_20180528T085641_N0206_R007_T36UVG_20180528T103122.SAFE
#### dates à traiter 20180531
/opt/maja/repL1/T36UVG/S2A_MSIL1C_20180531T091031_N0206_R050_T36UVG_20180531T111240.SAFE
/opt/maja/Start_maja/DTM/*T36UVG*/*
#################################
#################################
/opt/maja/core/1.0/bin/maja -i /opt/maja/work/T36UVG/T36UVG/MAJA_1_0_S2AS2B_NATIF//in -o /opt/maja/repL2/T36UVG/T36UVG/MAJA_1_0_S2AS2B_NATIF/ -m L2BACKWARD -ucs /opt/maja/work/T36UVG/T36UVG/MAJA_1_0_S2AS2B_NATIF//userconf --TileId T36UVG &> /opt/maja/repL2/T36UVG/T36UVG/MAJA_1_0_S2AS2B_NATIF//S2B_MSIL1C_20180503T085559_N0206_R007_T36UVG_20180503T115055.SAFE.log
#################################
Initialisation mode with backward is longer
MAJA logfile: /opt/maja/repL2/T36UVG/T36UVG/MAJA_1_0_S2AS2B_NATIF//S2B_MSIL1C_20180503T085559_N0206_R007_T36UVG_20180503T115055.SAFE.log
#################################
/opt/maja/repL2/T36UVG/T36UVG/MAJA_1_0_S2AS2B_NATIF//S2?_OPER_SSC_L2VALD_T36UVG____20180503.DBL.DIR
pas de L2 pour : /opt/maja/repL2/T36UVG/T36UVG/MAJA_1_0_S2AS2B_NATIF//S2?_OPER_SSC_L2VALD_T36UVG____20180503.DBL.DIR
previous L2 : 
Traceback (most recent call last):
  File "start_maja.py", line 277, in <module>
    print "previous L2 : ", nomL2
NameError: name 'nomL2' is not defined
[root@localhost Start_maja]# 
```
[S2B_MSIL1C_20180503T085559_N0206_R007_T36UVG_20180503T115055.SAFE.log](https://github.com/olivierhagolle/Start_maja/files/2581162/S2B_MSIL1C_20180503T085559_N0206_R007_T36UVG_20180503T115055.SAFE.log)
